id: P85411E8E
initial_creation_type: ocr
source_metadata:
  volumes:
    30563e0f0d0740589f23da8e5570668a:
      base_file: v060.txt
      image_group_id: I1PD95905
      title: དབུ་མ་ལ་འཇུག་པའི་བཤད་པ།
      total_pages: 1913
      volume_number: 60
